services:
  db:
    ports:
      - "127.0.0.1:5433:5432"

  redis:
    ports:
      - "127.0.0.1:6380:6379"

  api:
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./api:/app/api
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload

  bot:
    volumes:
      - ./bot:/app/bot
    command: python -m bot.main
